// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8wDZ2dHd0e78pSZFuAUT99tO5WZ8MZCo',
    appId: '1:1084362060261:web:9724c630ec3c42b4263f0c',
    messagingSenderId: '1084362060261',
    projectId: 'bookoo-syncs',
    authDomain: 'bookoo-syncs.firebaseapp.com',
    storageBucket: 'bookoo-syncs.appspot.com',
    measurementId: 'G-E2685299FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG8m96KFZfIoTYtne0cfUAFFjIfWwzuyU',
    appId: '1:1084362060261:android:809a3f0d20c8a53a263f0c',
    messagingSenderId: '1084362060261',
    projectId: 'bookoo-syncs',
    storageBucket: 'bookoo-syncs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAURu5wPy_HltDbikX1Ld8weHkMlNWjxMI',
    appId: '1:1084362060261:ios:a6bf39533673db4d263f0c',
    messagingSenderId: '1084362060261',
    projectId: 'bookoo-syncs',
    storageBucket: 'bookoo-syncs.appspot.com',
    iosClientId: '1084362060261-ujri797bab0603cr89kjvjjs0p5h4k7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAURu5wPy_HltDbikX1Ld8weHkMlNWjxMI',
    appId: '1:1084362060261:ios:e4f8acea37110af8263f0c',
    messagingSenderId: '1084362060261',
    projectId: 'bookoo-syncs',
    storageBucket: 'bookoo-syncs.appspot.com',
    iosClientId: '1084362060261-7vdgsm0t9irg3nce9vhnjcja05as50v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookoo.RunnerTests',
  );
}
